### ISSUE TITLE
求助：如何修改 VMessAEAD 验证

### ISSUE THREAD

**Issue by marujun** [yonggekkk/x-ui-yg#11]
https://www.v2fly.org/config/protocols/vmess.html#vmess-md5-%E8%AE%A4%E8%AF%81%E4%BF%A1%E6%81%AF-%E6%B7%98%E6%B1%B0%E6%9C%BA%E5%88%B6

我发现alertId不为0的时候，客户端就连不上了；查了一下是这个环境变量的原因，求助： 在x-ui里如何设置这个环境变量

**Comment by yonggekkk** [comment]
现在一般都默认是0了
https://xtls.github.io/config/inbounds/vmess.html#vmess-md5-%E8%AE%A4%E8%AF%81%E4%BF%A1%E6%81%AF-%E7%8E%B7%E6%B1%A1%E6%9C%BA%E5%88%B6

**Comment by marujun** [comment]
> 现在都默认直接为0了 https://xtls.github.io/config/inbounds/vmess.html#vmess-md5-%E8%AE%A4%E8%AF%81%E4%BF%A1%E6%81%AF-%E7%8E%B7%E6%B1%A1%E6%9C%BA%E5%88%B6

大佬，我想换x-ui，但是之前的配置已经分享给好几个朋友了，不想让他们去修改配置，所以我只能在vps上设置 v2ray.vmess.aead.forced=false 关闭VMessAEAD验证；如果想要设置这个环境变量有办法可以做到吗？

**Comment by yonggekkk** [comment]
> > 现在都默认直接为0了 https://xtls.github.io/config/inbounds/vmess.html#vmess-md5-%E8%AE%A4%E8%AF%81%E4%BF%A1%E6%81%AF-%E7%8E%B7%E6%B1%A1%E6%9C%BA%E5%88%B6
> 
> @yonggekkk 大佬，我之前的配置已经分享给好几个朋友了，不想让他们去修改配置，所以只能我在vps上设置 v2ray.vmess.aead.forced=false 关闭VMessAEAD验证；如果想要设置这个环境变量有办法可以做到吗？

这个去Xray项目那提问吧
