### ISSUE TITLE
gitlab 403 forbidden

### ISSUE THREAD

**Issue by kanelau** [yonggekkk/x-ui-yg#19]
gitlab不让访问是啥情况？

**Comment by yonggekkk** [comment]
发下日志

**Comment by kanelau** [comment]
![IMG_20230803_180448.jpg](https://github.com/yonggekkk/x-ui-yg/assets/17211768/78908844-f7b5-4795-9474-b0634743ac07)

**Comment by yonggekkk** [comment]
不知你是怎么运行的！防火墙选择菜单也没有
