### ISSUE TITLE
甬哥求解

### ISSUE THREAD

**Issue by seagullz4** [yonggekkk/x-ui-yg#2]
我买了台上海的服务器，安装之后为什么可以正常连接，但是却不能正常访问网络

甬哥求解

**Comment by yonggekkk** [comment]
为什么不买国外？！

**Comment by seagullz4** [comment]
有国外的，但是我用另外一个大佬的那个chatgpt仓库登陆qq需要用到相同网络环境，就是与服务器相同的IP环境才能正常登陆😂
