### ISSUE TITLE
之前安装的vaxliu版本，可以之前再安装你这个么？

### ISSUE THREAD

**Issue by kentcc88** [yonggekkk/x-ui-yg#20]
大佬，我已经安装了vaxliu版本，但感觉你的好用些，可以使用你的安装命令覆盖吗？数据会不会消失？

**Comment by yonggekkk** [comment]
卸载重装吧！节点备份下

**Comment by kentcc88** [comment]
> 卸载重装吧！节点备份下

怎么备份啊，能教我一下吗？或者网上有啥教程贴上来。。原版本没有备份按钮，不知道用什么命令或者方法备份现有的节点

**Comment by yonggekkk** [comment]
> > 卸载重装吧！节点备份下
> 
> 怎么备份啊，能教我一下吗？或者网上有啥教程贴上来。。原版本没有备份按钮，不知道用什么命令或者方法备份现有的节点

节点很多吗？那没办法，一个一个来了

**Comment by kentcc88** [comment]
> > > 卸载重装吧！节点备份下
> > 
> > 
> > 怎么备份啊，能教我一下吗？或者网上有啥教程贴上来。。原版本没有备份按钮，不知道用什么命令或者方法备份现有的节点
> 
> 节点很多吗？那没办法，一个一个来了

节点是很多。。。额，没有什么打包的方法么？小悲催一下
