### ISSUE TITLE
请求添加自定义出站节点功能

### ISSUE THREAD

**Issue by Ren9527** [yonggekkk/x-ui-yg#24]
我有大陆的服务器，需要搭建中转跳板机，但我小白一个，改写的xui配置文件总不通，希望勇哥能在一键脚本中添加此项功能。

**Comment by yonggekkk** [comment]
自带了dokodemo-door

**Comment by Ren9527** [comment]
那大佬 出点教程吧，小白一个不会整。。。
&nbsp;


被遗忘的
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月31日(星期二) 下午2:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yonggekkk/x-ui-yg] 请求添加自定义出站节点功能 (Issue #24)





 
自带了dokodemo-door
