### ISSUE TITLE
x-ui提示更新，更新后 x-ui命令无法唤醒脚本

### ISSUE THREAD

**Issue by Ren9527** [yonggekkk/x-ui-yg#25]
提示找不到 x-ui

**Comment by Ren9527** [comment]
但web页正常

**Comment by Ren9527** [comment]
[x-ui.log](https://github.com/yonggekkk/x-ui-yg/files/13218820/x-ui.log)

**Comment by yonggekkk** [comment]
如果是很早的脚本更新，建议重装下

**Comment by Ren9527** [comment]
重装之后也提示更新

**Comment by Ren9527** [comment]
我今天刚刚安装的，下午刚刚请求添加自定义出站的问题也是我提的

**Comment by Ren9527** [comment]
现在两条一键安装命令都不起作用

**Comment by yonggekkk** [comment]
必须ROOT目录运行脚本

**Comment by yonggekkk** [comment]
> > 必须ROOT目录运行脚本
> > ![image](https://user-images.githubusercontent.com/24719953/279450145-81f5fb95-1901-439b-a67a-08c28d2125e2.png

> > 必须ROOT目录运行脚本
> > ![image](https://user-images.githubusercontent.com/24719953/279450145-81f5fb95-1901-439b-a67a-08c28d2125e2.png)

试下别的脚本能正常运行吗
