### ISSUE TITLE
有后门，真无耻，安装后每天都来扫admin账户的密码

### ISSUE THREAD

**Issue by Anole47** [yonggekkk/x-ui-yg#26]
用十台VPS测试，其中3台安装了你的x-ui，毫无例外这3台的地址都被泄露，每天被扫登陆密码，真够无耻，无下线，直播还冠免堂皇说没有后台，你可真够狗的！从此拉黑！

**Comment by yonggekkk** [comment]
建议公布复现过程，可领10万奖金

**Comment by Anole47** [comment]
![截图](https://github.com/yonggekkk/x-ui-yg/assets/115643931/dfe0f3de-9abc-441e-880e-6c03bed3b0f5)
我是小白，搞不了复现，给你看看被扫的提示，你自己想想吧

**Comment by yonggekkk** [comment]
> ![截图](https://private-user-images.githubusercontent.com/115643931/292608068-dfe0f3de-9abc-441e-880e-6c03bed3b0f5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMDU1OTAsIm5iZiI6MTcwMzMwNTI5MCwicGF0aCI6Ii8xMTU2NDM5MzEvMjkyNjA4MDY4LWRmZTBmM2RlLTlhYmMtNDQxZS04ODBlLTZjMDNiZWQzYjBmNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QwNDIxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjI5YzJlN2RjNTg3MTg2ZjVjN2VmNDQ2ZTVjZDJjM2Y0NjM0NWU1ZTU3MGNhM2QwMzdjNmUwMzJiYTE0M2VhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l9Lj8Fc4abHiApX-wewsqo2xqrgobmw2nv7ZUggWqSw) 我是小白，搞不了复现，给你看看被扫的提示，你自己想想吧

你这什么问题都说明不了。。想想为什么只发生在你一个人身上。可以来我群里说说

**Comment by yonggekkk** [comment]
确保你的VPS密码不容易被破，设置XUI时，用户名与密码要复杂点，一定要加上根路径

**Comment by yonggekkk** [comment]
> ![截图](https://private-user-images.githubusercontent.com/115643931/292608068-dfe0f3de-9abc-441e-880e-6c03bed3b0f5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMDY3MzUsIm5iZiI6MTcwMzMwNjQzNSwicGF0aCI6Ii8xMTU2NDM5MzEvMjkyNjA4MDY4LWRmZTBmM2RlLTlhYmMtNDQxZS04ODBlLTZjMDNiZWQzYjBmNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QwNDQwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjU2YzlhOWRkYjExMjIxNTM3YTFmYWVlMzYwNTExNWNjZjYzMWJlMTcyMmI2M2MyZTdkOGQ2ODFhYjNlNzczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BuQTWaHyoo5NdqWdZaXKRJGkhHm_HJcQ2i2rVMYuCnc) 我是小白，搞不了复现，给你看看被扫的提示，你自己想想吧

如果用此图就说脚本有后门？被大伙看到那又要闹笑话了。。先做好根路径吧

**Comment by Anole47** [comment]
我说一下我的情况吧，我有多台VPS都安装了XIU面板，其中3台用的你的教程和脚本，2台用波仔的教程脚本做，2台按奶油的教程脚本做，一直正常使用也快几个月了，账号密码都是设置的高强度，也绑定了域名和证书在使用。
最近一个月才看了绑定电报通知的教程，就把所有XIU面板都绑定了，发现总有几台机器有陌生IP来扫admin的密码，就花了点时间，把所有的IP换了，域名也改了，但状况依旧。我才开始观察是哪几台会被扫，最终发现被扫的3台都是通过你的教程建的XUI面板，我把其中一台的XUI面板卸载了，换成波仔教程里的XIU面板，那台机器就没再被提示了。
所以判断你的脚本嫌疑最大。

**Comment by yonggekkk** [comment]
> 我说一下我的情况吧，我有多台VPS都安装了XIU面板，其中3台用的你的教程和脚本，2台用波仔的教程脚本做，2台按奶油的教程脚本做，一直正常使用也快几个月了，账号密码都是设置的高强度，也绑定了域名和证书在使用。 最近一个月才看了绑定电报通知的教程，就把所有XIU面板都绑定了，发现总有几台机器有陌生IP来扫admin的密码，就花了点时间，把所有的IP换了，域名也改了，但状况依旧。我才开始观察是哪几台会被扫，最终发现被扫的3台都是通过你的教程建的XUI面板，我把其中一台的XUI面板卸载了，换成波仔教程里的XIU面板，那台机器就没再被提示了。 所以判断你的脚本嫌疑最大。

陌生IP来扫admin的密码这是不受控制的，他想扫不扫这是不受控制的。。如果你非要把概率问题升级到后门层面，那我也无话可说。。。。

**Comment by Anole47** [comment]
> > 我说一下我的情况吧，我有多台VPS都安装了XIU面板，其中3台用的你的教程和脚本，2台用波仔的教程脚本做，2台按奶油的教程脚本做，一直正常使用也快几个月了，账号密码都是设置的高强度，也绑定了域名和证书在使用。 最近一个月才看了绑定电报通知的教程，就把所有XIU面板都绑定了，发现总有几台机器有陌生IP来扫admin的密码，就花了点时间，把所有的IP换了，域名也改了，但状况依旧。我才开始观察是哪几台会被扫，最终发现被扫的3台都是通过你的教程建的XUI面板，我把其中一台的XUI面板卸载了，换成波仔教程里的XIU面板，那台机器就没再被提示了。 所以判断你的脚本嫌疑最大。
> 
> 陌生IP来扫admin的密码这是不受控制的，说白了，那些扫XUI的蛆虫们想扫不扫这是不受控制的，再强调一次。。。。如果你非要把概率问题升级到后门层面，那我也无话可说。。。。

感谢勇哥的耐心对待与解释，让我明白了其中的问题所在。请原谅我的无知和冲动，对不起您。我收回所有的不敬，并会继续支持您的创作。

**Comment by yonggekkk** [comment]
> > > 我说一下我的情况吧，我有多台VPS都安装了XIU面板，其中3台用的你的教程和脚本，2台用波仔的教程脚本做，2台按奶油的教程脚本做，一直正常使用也快几个月了，账号密码都是设置的高强度，也绑定了域名和证书在使用。 最近一个月才看了绑定电报通知的教程，就把所有XIU面板都绑定了，发现总有几台机器有陌生IP来扫admin的密码，就花了点时间，把所有的IP换了，域名也改了，但状况依旧。我才开始观察是哪几台会被扫，最终发现被扫的3台都是通过你的教程建的XUI面板，我把其中一台的XUI面板卸载了，换成波仔教程里的XIU面板，那台机器就没再被提示了。 所以判断你的脚本嫌疑最大。
> > 
> > 
> > 陌生IP来扫admin的密码这是不受控制的，说白了，那些扫XUI的蛆虫们想扫不扫这是不受控制的，再强调一次。。。。如果你非要把概率问题升级到后门层面，那我也无话可说。。。。
> 
> 感谢勇哥的耐心对待与解释，让我明白了其中的问题所在。请原谅我的无知和冲动，对不起您。我收回所有的不敬，并会继续支持您的创作。

没事没事，说清楚了就行，有问题随便问
