### ISSUE TITLE
请问能不能制作docker版本

### ISSUE THREAD

**Issue by Akimio521** [yonggekkk/x-ui-yg#28]
如题，请问能不能制作docker版本，部署更加方便，本来想帮忙制作docker版本，但由于闭源，所以在这里问一下能不能帮忙制作一下docker版本

**Comment by yonggekkk** [comment]
> 如题，请问能不能制作docker版本，部署更加方便，本来想帮忙制作docker版本，但由于闭源，所以在这里问一下能不能帮忙制作一下docker版本

可以看下github其他版本的x-ui。。。他们多数支持docker

**Comment by Akimio521** [comment]
> > 如题，请问能不能制作docker版本，部署更加方便，本来想帮忙制作docker版本，但由于闭源，所以在这里问一下能不能帮忙制作一下docker版本
> 
> 
> 
> 可以看下github其他作者开源版本的x-ui。。。他们多数支持docker

主要是想使用warp

**Comment by yonggekkk** [comment]
> > > 如题，请问能不能制作docker版本，部署更加方便，本来想帮忙制作docker版本，但由于闭源，所以在这里问一下能不能帮忙制作一下docker版本
> > 
> > 
> > 可以看下github其他作者开源版本的x-ui。。。他们多数支持docker
> 
> 主要是想使用warp

这个可以通过脚本安装或者修改配置文件添加出站呀

**Comment by Akimio521** [comment]
我看了一下warp-cli，好像里面的socks代理只允许本机使用，有没有方法让局域网内的其他机器使用
