### ISSUE TITLE
关于脚本的gpt解锁功能，希望能让使用者自行选择开启或者关闭

### ISSUE THREAD

**Issue by 2604836155** [yonggekkk/x-ui-yg#29]
你好，vps商已经提供了自建dns的方式解锁gpt，但是您脚本的gpt解锁貌似会覆盖vps商的解锁功能，导致可用性变得很差，我搭了原版的xui测试，是可以正常稳点gpt，您脚本的这个功能可以关闭吗？

**Comment by yonggekkk** [comment]
删除openai分流那行，复制下面为yg kkk，保持一致就行

**Comment by yonggekkk** [comment]
Xui下回更新，视频教程我会再说下！
