### ISSUE TITLE
关于x-ui分流

### ISSUE THREAD

**Issue by Akimio521** [yonggekkk/x-ui-yg#31]
请问xray的配置文件应该怎么书写，想根据入站节点分流而不是域名分流
例如vless1，所以流量都会走warp-sock
vless2，入站后所有流量都会走vps原本的ipv4网卡

**Comment by yonggekkk** [comment]
目前脚本的配置仅支持简单的全局节点的域名分流，当然你可以自己修改其他方式

**Comment by Akimio521** [comment]
> 目前脚本的配置仅支持简单的全局节点的域名分流，当然你可以自己修改其他方式

请问我应该在哪里学习

**Comment by yonggekkk** [comment]
> > 目前脚本的配置仅支持简单的全局节点的域名分流，当然你可以自己修改其他方式
> 
> 请问我应该在哪里学习

谷歌下xray配置文档
