### ISSUE TITLE
一键脚本跑完没有及时按1安装xui，后续如何进入菜单安装xui面板？

### ISSUE THREAD

**Issue by 2604836155** [yonggekkk/x-ui-yg#32]
如下图，
更新：已解决，重新跑了一遍一键脚本安装了xui
更新2：但是如果后续想进入操作面板高bbr、acme、warp啥的，用什么命令进去呀？

**Comment by 2604836155** [comment]
![1706004819580](https://github.com/yonggekkk/x-ui-yg/assets/62831654/266032ac-d74a-44da-8330-c0f654ef836c)

**Comment by yonggekkk** [comment]
> ![1706004819580](https://private-user-images.githubusercontent.com/62831654/298895864-266032ac-d74a-44da-8330-c0f654ef836c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDk5NTIsIm5iZiI6MTcwNjAwOTY1MiwicGF0aCI6Ii82MjgzMTY1NC8yOTg4OTU4NjQtMjY2MDMyYWMtZDc0YS00NGRhLTgzMzAtYzBmNjU0ZWY4MzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDExMzQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NjkwZjgyODczNDEzNmY2YzRjMmZlNTZmNmQ5NWM5NGEzYmRhYzRlM2E0MDVlZmQyNDViYTg0ODU0Y2NjYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CpKKknUfn6S9T4G5Jt8bWnY08UABxRh0JPBUhxSSedo)

输入x-ui

**Comment by 2604836155** [comment]
> > ![1706004819580](https://private-user-images.githubusercontent.com/62831654/298895864-266032ac-d74a-44da-8330-c0f654ef836c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDk5NTIsIm5iZiI6MTcwNjAwOTY1MiwicGF0aCI6Ii82MjgzMTY1NC8yOTg4OTU4NjQtMjY2MDMyYWMtZDc0YS00NGRhLTgzMzAtYzBmNjU0ZWY4MzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDExMzQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NjkwZjgyODczNDEzNmY2YzRjMmZlNTZmNmQ5NWM5NGEzYmRhYzRlM2E0MDVlZmQyNDViYTg0ODU0Y2NjYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CpKKknUfn6S9T4G5Jt8bWnY08UABxRh0JPBUhxSSedo)
> 
> 输入x-ui



> > ![1706004819580](https://private-user-images.githubusercontent.com/62831654/298895864-266032ac-d74a-44da-8330-c0f654ef836c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDk5NTIsIm5iZiI6MTcwNjAwOTY1MiwicGF0aCI6Ii82MjgzMTY1NC8yOTg4OTU4NjQtMjY2MDMyYWMtZDc0YS00NGRhLTgzMzAtYzBmNjU0ZWY4MzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDExMzQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NjkwZjgyODczNDEzNmY2YzRjMmZlNTZmNmQ5NWM5NGEzYmRhYzRlM2E0MDVlZmQyNDViYTg0ODU0Y2NjYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CpKKknUfn6S9T4G5Jt8bWnY08UABxRh0JPBUhxSSedo)
> 
> 输入x-ui

> > ![1706004819580](https://private-user-images.githubusercontent.com/62831654/298895864-266032ac-d74a-44da-8330-c0f654ef836c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDk5NTIsIm5iZiI6MTcwNjAwOTY1MiwicGF0aCI6Ii82MjgzMTY1NC8yOTg4OTU4NjQtMjY2MDMyYWMtZDc0YS00NGRhLTgzMzAtYzBmNjU0ZWY4MzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDExMzQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NjkwZjgyODczNDEzNmY2YzRjMmZlNTZmNmQ5NWM5NGEzYmRhYzRlM2E0MDVlZmQyNDViYTg0ODU0Y2NjYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CpKKknUfn6S9T4G5Jt8bWnY08UABxRh0JPBUhxSSedo)
> 
> 输入x-ui
甬哥，我倒不是想进去xui面板呢，我是连xui面板都没按1安装，我要进入那个按1安装xui的面板这样子

**Comment by yonggekkk** [comment]
输入脚本时不要留空格，回车不要按二下
