### ISSUE TITLE
如果可以，增加一个Hysteria2协议的创建多好~

### ISSUE THREAD

**Issue by dbguo** [yonggekkk/x-ui-yg#33]
如果可以，增加一个Hysteria2协议的创建多好~

**Comment by yonggekkk** [comment]
X-UI只有XRAY内核，你可以再安装sing box脚本现实Hysteria2，项目地址https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality

**Comment by fjnpzh** [comment]
参考一下S-UI,几乎全协议，可辛苦勇哥在其基础上改上一版，一直都在用您几乎所有脚本，谢谢

**Comment by yonggekkk** [comment]
> 参考一下S-UI,几乎全协议，可辛苦勇哥在其基础上改上一版，一直都在用您几乎所有脚本，谢谢

UI方面并不擅长啦。。
