### ISSUE TITLE
添加了argo的固定隧道，到时间就down了

### ISSUE THREAD

**Issue by zkf0802** [yonggekkk/x-ui-yg#39]
![微信截图_20240605194832](https://github.com/yonggekkk/x-ui-yg/assets/34957036/b2f5874c-61dc-47a4-bf8b-efd29021f978)
我有两台vps，都用了你的xui，但是到时间就会down掉，我不确定这个时间是多久、是不是同时down的，这是我个人的问题吗？怎么解决

**Comment by yonggekkk** [comment]
今天很多人都同时出现这问题，应该CF服务器问题。。重启下VPS会恢复
