### ISSUE TITLE
请问trojan协议一个节点如何添加多个用户密码，以及如何查看每个用户的流量

### ISSUE THREAD

**Issue by willsilicon** [yonggekkk/x-ui-yg#42]
以及可不可以像trojan-go那样既能使用websocket+tls也能用普通的tcp+tls，现在用的是面板设置里的自定义config文件
命令行执行./xray api stats -s 127.0.0.1:62789报错:
failed to get stats: rpc error: code = Unknown desc = app/stats/command:  not found.
但是节点列表里显示的流量是对的
谢谢。

**Comment by yonggekkk** [comment]
这个不会拓展

**Comment by willsilicon** [comment]
感谢回复的挺快，刚看xray文档说是要执行xray api statsquery -s 127.0.0.1:62789和xray api statssys -s 127.0.0.1:62789，但是可能因为我没有设置邮箱用户名，现在看执行这命令返回的结果和实际使用量不一样，回头我再看看他代码里怎么调用的吧
