### ISSUE TITLE
求助：Debian10安装不了socat导致证书签发失败

### ISSUE THREAD

**Issue by stark81** [yonggekkk/x-ui-yg#43]
根据涌哥油管上那个使用Debian10的vps搭建vless节点的教程一步一步进行，发现socat安装不成功
![报错1](https://github.com/yonggekkk/x-ui-yg/assets/48707376/325ddc90-6365-48ef-bcab-ffe2873b8571)

然后在x-ui里申请证书失败了。先报了一个红色的警告，然后显示证书申请失败，脚本退出。
![报错2](https://github.com/yonggekkk/x-ui-yg/assets/48707376/74a22800-95f4-4a05-9123-920e90c8d701)

![报错3](https://github.com/yonggekkk/x-ui-yg/assets/48707376/e48420ca-83bb-40d7-b879-6f2131b225b8)

麻烦大佬帮忙看看怎么解决？谢谢🙏

**Comment by yonggekkk** [comment]
先运行apt install socat -y
如果还是报错，把系统升级到Debian12或者换ubuntu22.04

**Comment by stark81** [comment]
> 先运行apt install socat -y 如果还是报错，把系统升级到Debian12或者换ubuntu22.04

。。。之前是按照视频来购买的vps，就买的256M内存的，导致无法升级到Debian12和ubuntu22，升级的话会出现内核死机。之前也重装过vps的系统，每次按照视频的步骤都没问题，就这一次不知道为啥代理出问题，重装系统后就报了这个错误。不仅仅是vps这个代理有问题，cloudflare的worker代理也出问题了，不知道大佬有没有别的办法帮解决一下，谢谢

**Comment by yonggekkk** [comment]
换ub20戓18

**Comment by stark81** [comment]
> 换ub20戓18

换成Ubuntu18之后，可以安装socat了，但依然无法签发证书：

- Invalid status, myrayssr.top:Verify error detail:DNS problem: server failure at resolver looking up TXT for _acme-challenge.myrayssr.top
- Please check log file for more details: /root/.acme.sh/acme.sh.log

![error-1111111](https://github.com/yonggekkk/x-ui-yg/assets/48707376/a83c6136-ab86-4bdf-826e-6314839ffe4d)

**Comment by stark81** [comment]
还是不行，找时间创建一个新的cloudflare账号，跟着视频重新试试吧。。
