### ISSUE TITLE
x-ui 无法进入，“syntax error near unexpected token `newline'"

### ISSUE THREAD

**Issue by wangduokai** [yonggekkk/x-ui-yg#44]
![image](https://github.com/user-attachments/assets/7f0e4e86-82f9-4a51-9d88-dcb3cc674db6)

**Comment by yonggekkk** [comment]
卸载重装下看

**Comment by wangduokai** [comment]
> 卸载重装下看

x-ui命令进不去，怎么卸载呀？

**Comment by yonggekkk** [comment]
输入脚本

**Comment by wangduokai** [comment]
> 输入脚本

请问输入什么脚本可以卸载？

**Comment by yonggekkk** [comment]
> > 输入脚本
> 
> 请问输入什么脚本可以卸载？

bash <(curl -Ls https://raw.githubusercontent.com/yonggekkk/x-ui-yg/main/install.sh)
