### ISSUE TITLE
订阅链接输出失败

### ISSUE THREAD

**Issue by DamonLee35** [yonggekkk/x-ui-yg#45]
输出订阅链接失败，输出的配置文件中没有节点信息
<img width="930" alt="Snipaste_2024-08-06_10-49-56" src="https://github.com/user-attachments/assets/516f1d3d-c433-4817-b6f8-7e0f839b075f">

**Comment by yonggekkk** [comment]
只有视频介绍中那几类节点才可以。。安装过程中有报错吗？是不是某些依赖没安装成功？

**Comment by DamonLee35** [comment]
已经安装很久了，v2ray至今正常使用，之前输出过一次singbox配置文件正常，可以正常连接，今天不知道是不是更新了下脚本的问题，再次输出就是图上的情况

**Comment by yonggekkk** [comment]
备份下，重装下看吧
