### ISSUE TITLE
一键申请acme证书有bug,cname问题

### ISSUE THREAD

**Issue by 300git** [yonggekkk/x-ui-yg#49]
当使用cname的域名进行申请时, 尽管解析出来的ip与本机检测一致, 也会提示不一致
例: 
>a.com 地址是1.1.1.1
b.com 直接cname a.com的地址
当使用a.com申请时, 一切正常
当使用b.com申请时,就会报错, 

这个问题当我在使用其他类似一键申请的脚本时候,不会发生,仅在您这发生
>如:[mack-a/v2ray-agent](https://github.com/mack-a/v2ray-agent),不会发生这个问题

并且您的其他项目中, 只要含有申请acme证书都会出现这个问题
>如您的[sing-box-yg](https://github.com/yonggekkk/sing-box-yg)

### 示例:
当使用b.com申请时,
使用的是
`1. acme.sh申请letsencrypt ECC证书（支持80端口模式与DNS API模式)` 中的**dns api模式**
使用的是cloudflare, 没有打开小黄云

>报错:
当前域名解析到的IPV4地址：a.com.
1.1.1.1
当前VPS本地的IP：1.1.1.1
当前域名解析的IP与当前VPS本地的IP不匹配！！！

会发现, 解析到了a.com和a.com的ipv4地址,   并且ipv4和本机检测地址是一致, 依然无法通过
ipv6也有这个问题

**Comment by yonggekkk** [comment]
最好让我实践下

**Comment by yonggekkk** [comment]
当前域名解析到的IPV4地址：host-us1.0007.fun.
152.135.12.34

host-us1.0007.fun.这是什么
