### ISSUE TITLE
使用curl命令进行安装会报错

### ISSUE THREAD

**Issue by kepy909** [yonggekkk/x-ui-yg#5]
使用：”bash <(curl -Ls https://gitlab.com/rwkgyg/x-ui-yg/raw/main/install.sh)“，进行安装会提示没有wget，导致下载x-ui包失败，建议优化。

**Comment by yonggekkk** [comment]
不会吧！第一次安装会自己检测安装的呀

**Comment by kepy909** [comment]
我也觉得不应该，但实际发生了，纯净系统下，是没有wget的。
运行wget安装直接无反应，也不提示需要安装wget和错误（我估计是这个问题导致的）。
VPS系统信息如下：
操作系统:   Rocky Linux release 8.8 (Green Obsidian)
内核版本:   4.18.0
CPU架构 :   amd64
虚拟化类型: kvm

**Comment by yonggekkk** [comment]
> 我也觉得不应该，但实际发生了，纯净系统下，是没有wget的。 运行wget安装直接无反应，也不提示需要安装wget和错误（我估计是这个问题导致的）。 VPS系统信息如下： 操作系统: Rocky Linux release 8.8 (Green Obsidian) 内核版本: 4.18.0 CPU架构 : amd64 虚拟化类型: kvm

原来是rocky系统，脚本要改下了！到时更新下

**Comment by kepy909** [comment]
搞定了？这么早

**Comment by yonggekkk** [comment]
> 搞定了？这么早

到时大版本更新加入吧，现在你先手动

**Comment by kepy909** [comment]
我手动没问题嘞，yum一个wget就好了，看你这么早，来打个招呼。

**Comment by yonggekkk** [comment]
> 我手动没问题嘞，yum一个wget就好了，看你这么早，来打个招呼。

你测试重装下，应该好了

**Comment by kepy909** [comment]
好的，辛苦
