### ISSUE TITLE
v24.12.18 Xray 状态: error

### ISSUE THREAD

**Issue by AugustRothchild** [yonggekkk/x-ui-yg#54]
Xray 24.12.18 (Xray, Penetrates Everything.) cab2fde (go1.23.4 linux/arm64)

A unified platform for anti-censorship.

2024/12/27 08:01:25 [Info] infra/conf/serial: Reading config: &{Name:bin/config.json Format:json}

Failed to start: main: failed to load config files: [bin/config.json] > common/errors: The feature HTTP transport (without header padding, etc.) has been removed and migrated to XHTTP stream-one H2 & H3. Please update your config(s) according to release note and documentation.
谷歌翻译：
Xray 24.12.18 (Xray，穿透一切。) cab2fde (go1.23.4 linux/arm64)

一个统一的反审查平台。

2024/12/27 08:00:01 [信息] infra/conf/serial：读取配置：&{Name:bin/config.json Format:json}

启动失败：main：加载配置文件失败：[bin/config.json] > common/errors：HTTP 传输功能（无标头填充等）已被删除并迁移到 XHTTP stream-one H2 和 H3。请根据发行说明和文档更新您的配置。

大佬，请问应该如何处理啊？

**Comment by yonggekkk** [comment]
菜单中点击更新脚本

**Comment by yonggekkk** [comment]
> 大佬，我也注意到了x-ui的版本问题，我点击了“6. 更新 x-ui 脚本”，但是更新完成后依旧显示“当前 x-ui-yg 脚本最新版：v24.9.14 (已安装)”，我时常更新版本，但是总是“当前 x-ui-yg 脚本最新版：v24.9.14 (已安装)”

当然是这样！我没改版号！还是这问题就删除节点

**Comment by yonggekkk** [comment]
每删一个看下有没有变正常

**Comment by yonggekkk** [comment]
换个WARP_WG账号

**Comment by lunaleevip** [comment]
xray 有办法看到日志吗？我这边部署的也是一直出现xray error，我看了下是连接太多了，有办法限制吗？

**Comment by lunaleevip** [comment]
![微信截图_20241227101926](https://github.com/user-attachments/assets/f230b6e2-d55f-4e6e-8179-5c137f7447d5)
![微信截图_20241227101850](https://github.com/user-attachments/assets/f4a1f058-061e-45e1-a6a4-a4cdce94dba6)

**Comment by yonggekkk** [comment]
> xray 有办法看到日志吗？我这边部署的也是一直出现xray error，我看了下是连接太多了，有办法限制吗？

卸载重装下XUI

**Comment by lunaleevip** [comment]
> > xray 有办法看到日志吗？我这边部署的也是一直出现xray error，我看了下是连接太多了，有办法限制吗？
> 
> 卸载重装下XUI

我已经找到了问题原因：我开了个 clash.mate 的 docker服务，可能是使用的人太多，造成访问节点的并发连接太多，直接把xray 给搞崩溃了
