### ISSUE TITLE
对openai的分流规则失效，更换warp账户三要素也都无法使用，删除了“geosite:openai”后还可登录网页版，加上后连网页版都进不去

### ISSUE THREAD

**Issue by AugustRothchild** [yonggekkk/x-ui-yg#55]
如题

**Comment by yonggekkk** [comment]
你卸载重装下试试

**Comment by yonggekkk** [comment]
> 卸载重装了x-ui，重新设置了节点，然后将“geosite:openai”依次替代6个通道的"yg_kkk"，均不能实现ios手机正常连接chatgpt客户端。删除了倒是可以登录网页版与电脑版客户端。

只能填一次。填6次干嘛

**Comment by AugustRothschild** [comment]
大佬，我现在只把“geosite:openai”只填在了"xray-wg-warp-v6"这个通道下，手机的ChatGPT也是没法正常连接，一直在接入刷新。
