### ISSUE TITLE
甬哥 反馈一个bug

### ISSUE THREAD

**Issue by ponyhaha** [yonggekkk/x-ui-yg#56]
用最新版的x-ui-yg部署，部署好之后，第一次设置了argo的端口是8880；系统生成了“vm-argo临时-8880  ”和“vm-argo固定-8880”固定两个节点名称。因为某种原因，需要更换端口，但是端口更换为2052，都设置成功之后，重新生成的配置里面还是“vm-argo临时-8880  ”和“vm-argo固定-8880”这两个节点，而且节点的端口也保持是8880。尝试卸载argo临时/固定隧道后，重新按2052端口配置，配置后生成的节点文件依然是8880端口的那个。

**Comment by yonggekkk** [comment]
ARGO默认都是8880或者8443，与XUI端口节点无关。。

**Comment by ponyhaha** [comment]
好的明白了，因为我是多台服务器，组合时候会提示重名，检查下才发现这个，现在理解了，谢谢。
